# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac873ddd048bf8e6899689b112060e8b505f9f5160802363164bda6c91f6cc76f218a0ac663ad96fe78566fc46b47ea75aafd719ca5b6bc0aaba1f05d967954d

test:
  secret_key_base: 2be95ebd5e9117cb9d4696082127ea0e097857e45dcf2f097143272e863d813f2ce92e68df36995b20f7040ed1660269fd30a3448a30c86b189fc3d75c80a94b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
